apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  managedBy: "platform-team"
  environment: "dev"
bases:
  - ../../../apps/webapp

namePrefix: dev-
replicas:
  - name: demo
    count: 3